version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=quriobot_shopify
      - MYSQL_ROOT_PASSWORD=quriobotmysqlpassword
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  api:
    container_name: quriobot-shopify-app
    build: ./
    image: quriobot-shopify-app
    depends_on:
      - db
    ports:
      - 8087:8087
    links:
      - db
    volumes:
      - ./:/app
volumes:
  db:
    driver: local